In [4]:
import pandas as pd
from google.colab import files

uploaded = files.upload()
df = pd.read_csv('customer_shopping_behavior.csv')

Saving customer_shopping_behavior.csv to customer_shopping_behavior (1).csv

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.describe(include='all')

In [ ]:
df.isnull().sum()

In [12]:
# Imputing missing values in Review Rating column
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

KeyError: 'Category'

In [7]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [9]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [10]:
#group by age
labels=['young adult','adult','middle age','senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [11]:
df[['age','age_group']].head(20)

    age    age_group
0    55   middle age
1    19  young adult
2    50   middle age
3    21  young adult
4    45   middle age
5    46   middle age
6    63       senior
7    27  young adult
8    26  young adult
9    57   middle age
10   53   middle age
11   30  young adult
12   61       senior
13   65       senior
14   64       senior
15   64       senior
16   25  young adult
17   53   middle age
18   52   middle age
19   66       senior

In [13]:
#create column purchase_frequency_days
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [14]:
df[['purchase_frequency_days','frequency_of_purchases']].head(20)

    purchase_frequency_days frequency_of_purchases
0                        14            Fortnightly
1                        14            Fortnightly
2                         7                 Weekly
3                         7                 Weekly
4                       365               Annually
5                         7                 Weekly
6                        90              Quarterly
7                         7                 Weekly
8                       365               Annually
9                        90              Quarterly
10                       14              Bi-Weekly
11                       14            Fortnightly
12                       14            Fortnightly
13                        7                 Weekly
14                        7                 Weekly
15                       30                Monthly
16                       14              Bi-Weekly
17                       90              Quarterly
18                        7                 Weekly
19                       14              Bi-Weekly

In [16]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [17]:
df=df.drop('promo_code_used',axis=1)

In [18]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [19]:
df.to_csv("customer_behavior_cleaned.csv", index=False)

In [20]:
from google.colab import files
files.download("customer_behavior_cleaned.csv")